In [1]:
import pandas as pd
import requests

In [2]:
url = "https://bank.gov.ua/NBU_Exchange/exchange?json"
response = requests.get(url)
data = response.json()
data

[{'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '036',
  'CurrencyCodeL': 'AUD',
  'Units': 1,
  'Amount': 24.7697},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '944',
  'CurrencyCodeL': 'AZN',
  'Units': 1,
  'Amount': 21.5515},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '933',
  'CurrencyCodeL': 'BYN',
  'Units': 1,
  'Amount': 13.2919},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '975',
  'CurrencyCodeL': 'BGN',
  'Units': 1,
  'Amount': 20.6602},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '410',
  'CurrencyCodeL': 'KRW',
  'Units': 100,
  'Amount': 2.8145},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '344',
  'CurrencyCodeL': 'HKD',
  'Units': 1,
  'Amount': 4.6585},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '208',
  'CurrencyCodeL': 'DKK',
  'Units': 1,
  'Amount': 5.4245},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '840',
  'CurrencyCodeL': 'USD',
  'Units': 1,
  'Amount': 36.5686},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '978',
  'CurrencyCodeL': 'EUR',
  'Units': 1,
  'Amount': 40.4174},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '818',
  'CurrencyCodeL': 'EGP',
  'Units': 1,
  'Amount': 1.1834},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '392',
  'CurrencyCodeL': 'JPY',
  'Units': 10,
  'Amount': 2.7574},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '985',
  'CurrencyCodeL': 'PLN',
  'Units': 1,
  'Amount': 8.7002},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '356',
  'CurrencyCodeL': 'INR',
  'Units': 10,
  'Amount': 4.4673},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '124',
  'CurrencyCodeL': 'CAD',
  'Units': 1,
  'Amount': 27.4415},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '484',
  'CurrencyCodeL': 'MXN',
  'Units': 1,
  'Amount': 2.0233},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '498',
  'CurrencyCodeL': 'MDL',
  'Units': 1,
  'Amount': 2.0353},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '376',
  'CurrencyCodeL': 'ILS',
  'Units': 1,
  'Amount': 9.9966},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '554',
  'CurrencyCodeL': 'NZD',
  'Units': 1,
  'Amount': 22.9687},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '578',
  'CurrencyCodeL': 'NOK',
  'Units': 1,
  'Amount': 3.5423},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '710',
  'CurrencyCodeL': 'ZAR',
  'Units': 1,
  'Amount': 2.0253},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '643',
  'CurrencyCodeL': 'RUB',
  'Units': 10,
  'Amount': 4.4803},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '946',
  'CurrencyCodeL': 'RON',
  'Units': 1,
  'Amount': 8.1785},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '360',
  'CurrencyCodeL': 'IDR',
  'Units': 1000,
  'Amount': 2.487},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '702',
  'CurrencyCodeL': 'SGD',
  'Units': 1,
  'Amount': 27.5636},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '960',
  'CurrencyCodeL': 'XDR',
  'Units': 1,
  'Amount': 49.518},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '398',
  'CurrencyCodeL': 'KZT',
  'Units': 100,
  'Amount': 8.1058},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '949',
  'CurrencyCodeL': 'TRY',
  'Units': 1,
  'Amount': 1.8876},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '348',
  'CurrencyCodeL': 'HUF',
  'Units': 100,
  'Amount': 10.8111},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '826',
  'CurrencyCodeL': 'GBP',
  'Units': 1,
  'Amount': 45.6852},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '203',
  'CurrencyCodeL': 'CZK',
  'Units': 1,
  'Amount': 1.7313},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '752',
  'CurrencyCodeL': 'SEK',
  'Units': 1,
  'Amount': 3.5602},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '756',
  'CurrencyCodeL': 'CHF',
  'Units': 1,
  'Amount': 41.1322},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '156',
  'CurrencyCodeL': 'CNY',
  'Units': 1,
  'Amount': 5.3354},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '012',
  'CurrencyCodeL': 'DZD',
  'Units': 10,
  'Amount': 2.6987},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '764',
  'CurrencyCodeL': 'THB',
  'Units': 10,
  'Amount': 10.7082},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '986',
  'CurrencyCodeL': 'BRL',
  'Units': 1,
  'Amount': 7.1775},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '051',
  'CurrencyCodeL': 'AMD',
  'Units': 100,
  'Amount': 9.4133},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '784',
  'CurrencyCodeL': 'AED',
  'Units': 1,
  'Amount': 9.9566},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '214',
  'CurrencyCodeL': 'DOP',
  'Units': 10,
  'Amount': 6.6857},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '704',
  'CurrencyCodeL': 'VND',
  'Units': 1000,
  'Amount': 1.5582},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '368',
  'CurrencyCodeL': 'IQD',
  'Units': 100,
  'Amount': 2.7915},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '364',
  'CurrencyCodeL': 'IRR',
  'Units': 10000,
  'Amount': 8.7068},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '981',
  'CurrencyCodeL': 'GEL',
  'Units': 1,
  'Amount': 14.3288},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '422',
  'CurrencyCodeL': 'LBP',
  'Units': 100,
  'Amount': 0.2438},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '434',
  'CurrencyCodeL': 'LYD',
  'Units': 1,
  'Amount': 7.6487},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '458',
  'CurrencyCodeL': 'MYR',
  'Units': 1,
  'Amount': 8.2822},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '504',
  'CurrencyCodeL': 'MAD',
  'Units': 1,
  'Amount': 3.5755},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '901',
  'CurrencyCodeL': 'TWD',
  'Units': 10,
  'Amount': 11.9936},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '586',
  'CurrencyCodeL': 'PKR',
  'Units': 10,
  'Amount': 1.2903},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '682',
  'CurrencyCodeL': 'SAR',
  'Units': 1,
  'Amount': 9.7441},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '941',
  'CurrencyCodeL': 'RSD',
  'Units': 10,
  'Amount': 3.3893},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '417',
  'CurrencyCodeL': 'KGS',
  'Units': 10,
  'Amount': 4.1831},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '972',
  'CurrencyCodeL': 'TJS',
  'Units': 1,
  'Amount': 3.3507},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '050',
  'CurrencyCodeL': 'BDT',
  'Units': 10,
  'Amount': 3.4305},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '788',
  'CurrencyCodeL': 'TND',
  'Units': 1,
  'Amount': 11.9595},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '934',
  'CurrencyCodeL': 'TMT',
  'Units': 1,
  'Amount': 10.4482},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '860',
  'CurrencyCodeL': 'UZS',
  'Units': 1000,
  'Amount': 3.1985},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '959',
  'CurrencyCodeL': 'XAU',
  'Units': 1,
  'Amount': 74349.08},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '961',
  'CurrencyCodeL': 'XAG',
  'Units': 1,
  'Amount': 950.17},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '962',
  'CurrencyCodeL': 'XPT',
  'Units': 1,
  'Amount': 38381.67},
 {'StartDate': '17.04.2023',
  'TimeSign': '0000',
  'CurrencyCode': '964',
  'CurrencyCodeL': 'XPD',
  'Units': 1,
  'Amount': 54422.85}]

In [3]:
pd.DataFrame(data).to_csv('csvdata')

In [4]:
import boto3
s3 = boto3.client('s3')

In [5]:
s3.upload_file('csvdata.csv', 'bucket77', 'csvdata_1.csv')

In [ ]:
import boto3

# create an S3 client object
s3 = boto3.client('s3',
                  aws_access_key_id='AKIA4DJ3SVIVESWX53BL',
                  aws_secret_access_key='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')

# specify the bucket and object key
bucket_name = 'bucket77'
object_key = 'csvdata.csv'

# read the file contents
response = s3.get_object(Bucket=bucket_name, Key=object_key)
data = response['Body'].read().decode('utf-8')

# print the file contents
print(data)

In [ ]:
from io import StringIO
df = pd.read_csv(StringIO(data))
df.drop(columns = ['Unnamed: 0'], inplace=True)

### DATA of $

In [ ]:
import requests
import pandas as pd

url = "https://bank.gov.ua/NBU_Exchange/exchange_site?start=20220115&end=20220131&valcode=usd&sort=exchangedate&order=desc&json"
response = requests.get(url)
data = response.json()
dollars = pd.DataFrame(data)

In [ ]:
import matplotlib.pyplot as plt

plt.plot(list(dollars['calcdate']), list(dollars['rate_per_unit']))
plt.xticks(rotation=90)
plt.xlabel('data')
plt.ylabel('rate per unit')
plt.title('rate of dollar')
plt.savefig('dolars.png')

In [ ]:
import boto3
s3 = boto3.client('s3',
                  aws_access_key_id='AKIA4DJ3SVIVESWX53BL',
                  aws_secret_access_key='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')

s3.upload_file('dolars.png', 'bucket77', 'dolars.png')